const BASIC_PORTUGUESE_QUESTIONS = {
    "Qual é o plural de 'cão'?": ["cães", "cãos", "cãones", "cãon"],
    "Qual dessas palavras é um verbo?": ["correr", "bola", "feliz", "livro"],
    "Qual é o antônimo de 'alegre'?": ["triste", "contente", "feliz", "risonho"],
    "Em qual palavra há encontro consonantal?": ["prato", "asa", "casa", "fada"],
    "Qual dessas palavras está escrita corretamente?": ["abacaxi", "abachaxi", "abacachí", "abacashí"],
    "O que é um substantivo?": ["É uma palavra que dá nome a seres, objetos ou lugares", "É uma ação", "É uma qualidade", "É um som"],
    "Escolha a frase com verbo no presente:": ["Eu estudo todos os dias.", "Ontem eu estudei muito.", "Amanhã eu estudarei.", "Estudaria se pudesse."],
    "Qual dessas frases está com a pontuação correta?": ["Que dia bonito!", "Que dia bonito", "Que dia bonito?", "Que dia bonito."],
    "Assinale a palavra que é um adjetivo:": ["bonito", "correr", "mesa", "livro"],
    "Qual é o diminutivo de 'flor'?": ["florzinha", "florão", "flores", "florzão"],
    "Qual palavra está no aumentativo?": ["casarão", "casinha", "casa", "casinhas"],
    "Complete: A _____ é azul.": ["bola", "bonita", "correr", "feliz"],
    "Qual dessas palavras é um substantivo próprio?": ["Brasil", "país", "cidade", "menino"],
    "Escolha a palavra que rima com 'pato'.": ["sapato", "gato", "carro", "mesa"],
    "Complete com o verbo correto: Ela _____ muito bem.": ["canta", "cantou", "cantará", "cantar"],
    "Assinale a palavra no feminino:": ["menina", "menino", "cachorro", "garoto"],
    "Qual dessas frases tem uma interjeição?": ["Ai! Isso dói.", "Ele corre rápido.", "O carro é azul.", "Ela gosta de ler."],
    "O que é uma sílaba?": ["É cada pedacinho sonoro de uma palavra", "É uma frase", "É um texto", "É uma letra"],
    "Quantas sílabas tem a palavra 'banana'?": ["3", "2", "4", "5"],
    "Qual palavra tem dígrafo?": ["chave", "pato", "bola", "mesa"],
    "Escolha a opção que é um pronome pessoal.": ["eu", "correr", "mesa", "feliz"],
    "O que é um artigo definido?": ["É aquele que define o substantivo (o, a, os, as)", "É um verbo", "É uma qualidade", "É um som"],
    "Qual palavra está no plural?": ["livros", "livro", "escola", "cadeira"],
    "O que significa o prefixo 're-' em 'recomeçar'?": ["fazer de novo", "fazer errado", "fazer bonito", "fazer pequeno"],
    "Complete com a preposição correta: Ela gosta _____ música.": ["de", "em", "para", "com"],
    "O que é uma onomatopeia?": ["Palavra que imita um som", "Palavra difícil", "Palavra grande", "Palavra com acento"],
    "Assinale a palavra com acento agudo:": ["fácil", "feliz", "pato", "menino"],
    "Qual é o plural de 'pão'?": ["pães", "pãos", "pãones", "pãon"],
    "Qual é o coletivo de 'abelhas'?": ["enxame", "bando", "manada", "cardume"],
    "Complete: O _____ é verde.": ["gramado", "correr", "feliz", "bonito"],
    "O que é um advérbio?": ["Palavra que indica circunstância", "Nomeia objetos", "Indica uma ação", "É um som"],
    "Assinale a alternativa com verbo no passado:": ["corri", "corro", "correndo", "correrei"],
    "O que é sujeito da frase?": ["É quem faz ou sofre a ação", "É a ação", "É o local", "É o tempo"],
    "Assinale a palavra com encontro vocálico:": ["saída", "prato", "mesa", "gato"],
    "O que é uma interjeição?": ["Expressão de emoção ou sentimento", "Verbo", "Adjetivo", "Artigo"],
    "Qual dessas palavras tem dígrafo?": ["chave", "bola", "mesa", "livro"],
    "Escolha a palavra que tem encontro consonantal:": ["prato", "asa", "casa", "fada"],
    "O que é uma frase?": ["Conjunto de palavras com sentido completo", "Uma sílaba", "Uma letra", "Um som"],
    "Complete: Eu _____ feliz hoje.": ["estou", "estive", "estaria", "estarei"],
    "Qual é o aumentativo de 'casa'?": ["casarão", "casinha", "casas", "casebre"],
    "Escolha a opção que é um adjetivo:": ["feliz", "bola", "livro", "mesa"],
    "Complete: Eles _____ futebol.": ["jogam", "jogou", "jogaria", "jogarão"],
    "O que significa 'antônimo'?": ["Palavra de sentido contrário", "Palavra igual", "Palavra engraçada", "Palavra grande"],
    "Qual é o coletivo de 'peixes'?": ["cardume", "enxame", "manada", "bando"],
    "Qual dessas palavras tem acento circunflexo?": ["você", "feliz", "bola", "menino"],
    "Complete com o artigo definido: ____ escola é grande.": ["A", "Uma", "Uma escola", "Nenhuma"],
    "Qual dessas palavras indica uma ação?": ["brincar", "bola", "bonito", "feliz"],
    "O que é um parônimo?": ["Palavra parecida na escrita e pronúncia, mas com significados diferentes", "Palavra contrária", "Palavra igual", "Palavra pequena"],
    "Escolha a frase que tem verbo no futuro:": ["Eu viajarei amanhã.", "Eu viajei ontem.", "Eu viajava sempre.", "Eu viajo agora."]
};

const BASIC_SCIENCE_QUESTIONS = {
    "Qual é o maior órgão do corpo humano?": ["Pele", "Coração", "Pulmão", "Estômago"],
    "O que as plantas precisam para fazer fotossíntese?": ["Luz solar", "Sal", "Açúcar", "Leite"],
    "Qual planeta é conhecido como Planeta Vermelho?": ["Marte", "Vênus", "Júpiter", "Saturno"],
    "Qual é a estrela mais próxima da Terra?": ["Sol", "Vênus", "Lua", "Marte"],
    "A água, quando congelada, vira:": ["Gelo", "Vapor", "Sal", "Areia"],
    "Os peixes respiram por meio de:": ["Brânquias", "Pulmões", "Bocas", "Narinas"],
    "O que usamos para ouvir sons?": ["Ouvido", "Olho", "Boca", "Nariz"],
    "Qual é o principal gás que respiramos?": ["Oxigênio", "Hidrogênio", "Gás carbônico", "Hélio"],
    "Quantos planetas há no sistema solar?": ["8", "7", "9", "10"],
    "O que é necessário para existir combustão?": ["Oxigênio", "Água", "Sal", "Areia"],
    "O que protege a Terra dos raios solares nocivos?": ["Camada de ozônio", "Nuvens", "Árvores", "Vento"],
    "Qual animal é um mamífero?": ["Leão", "Galinha", "Cobra", "Jacaré"],
    "Qual desses animais é um réptil?": ["Jacaré", "Gato", "Papagaio", "Cavalo"],
    "Qual órgão bombeia sangue no corpo?": ["Coração", "Pulmão", "Estômago", "Fígado"],
    "De onde vem a energia elétrica nas hidrelétricas?": ["Água", "Vento", "Sol", "Carvão"],
    "O que é necessário para as plantas crescerem?": ["Luz, água e nutrientes", "Som", "Fumaça", "Frio extremo"],
    "Qual planeta é conhecido por seus anéis?": ["Saturno", "Júpiter", "Marte", "Urano"],
    "Qual é o estado físico da água em temperaturas abaixo de 0°C?": ["Sólido", "Líquido", "Gasoso", "Plasma"],
    "O que significa reciclar?": ["Reutilizar materiais", "Jogar fora", "Queimar lixo", "Enterrar lixo"],
    "Qual desses animais é ovíparo?": ["Galinha", "Cachorro", "Gato", "Vaca"],
    "A Terra gira em torno de qual astro?": ["Sol", "Lua", "Marte", "Vênus"],
    "Qual é o nome do satélite natural da Terra?": ["Lua", "Sol", "Marte", "Estrela"],
    "Os morcegos são:": ["Mamíferos", "Aves", "Répteis", "Peixes"],
    "O que é necessário para que haja eco?": ["Reflexão do som", "Luz", "Vento", "Chuva"],
    "Qual desses alimentos é saudável?": ["Maçã", "Refrigerante", "Batata frita", "Bala"],
    "O que acontece com a água quando é aquecida a 100°C?": ["Vira vapor", "Vira gelo", "Fica sólida", "Desaparece"],
    "O que usamos para sentir cheiros?": ["Nariz", "Olhos", "Ouvidos", "Boca"],
    "Qual desses animais é aquático?": ["Peixe", "Cavalo", "Macaco", "Gato"],
    "O que é a fotossíntese?": ["Processo em que a planta produz seu alimento", "Plantas dormindo", "A planta chorando", "A planta correndo"],
    "Qual órgão é responsável pela respiração?": ["Pulmões", "Coração", "Fígado", "Estômago"],
    "O que é o habitat de um animal?": ["Local onde ele vive", "O que ele come", "O que ele faz", "Sua cor"],
    "Qual fase da água observamos nas nuvens?": ["Gasosa", "Líquida", "Sólida", "Vapor congelado"],
    "Qual desses é um astro?": ["Sol", "Avião", "Montanha", "Carro"],
    "O que é uma fonte de energia renovável?": ["Solar", "Petróleo", "Carvão", "Gás natural"],
    "O que acontece quando jogamos lixo nos rios?": ["Poluição", "Melhora da água", "Ajuda os peixes", "Aumenta os peixes"],
    "Qual desses animais tem coluna vertebral?": ["Cachorro", "Minhoca", "Polvo", "Lesma"],
    "O que acontece quando a luz é bloqueada?": ["Forma sombra", "Forma som", "Cria calor", "Forma água"],
    "A transformação da lagarta em borboleta é chamada de:": ["Metamorfose", "Crescimento", "Fotosíntese", "Evaporação"],
    "Qual destes é um mineral?": ["Ferro", "Árvore", "Gato", "Papel"],
    "Qual destes é um ser vivo?": ["Cacto", "Pedra", "Vento", "Areia"],
    "O que é necessário para uma planta viver?": ["Luz, água e solo", "Som", "Vento", "Fumaça"],
    "O que significa 'biodegradável'?": ["Que se decompõe na natureza", "Que nunca se quebra", "Que brilha", "Que queima rápido"],
    "Qual é o ciclo da água?": ["Evaporação, condensação e precipitação", "Combustão, expansão, evaporação", "Sublimação, fusão, combustão", "Fotosíntese, condensação, combustão"],
    "O que é uma estrela cadente?": ["Meteoro", "Estrela que caiu", "Sol", "Planeta"],
    "O que protege o embrião dentro do ovo?": ["Casca", "Pena", "Bico", "Ar"],
    "A chuva é resultado de qual fenômeno?": ["Condensação", "Evaporação", "Fusão", "Sublimação"],
    "O que são seres decompositores?": ["Fungos e bactérias", "Leões", "Plantas", "Elefantes"],
    "Qual destes alimentos é fonte de proteína?": ["Carne", "Bala", "Refrigerante", "Chocolate"],
    "O que é necessário para apagar o fogo?": ["Tirar o oxigênio", "Aumentar o calor", "Colocar mais combustível", "Bater palmas"],
    "Qual destes fenômenos naturais pode causar terremotos?": ["Movimento das placas tectônicas", "Chuva", "Vento", "Relâmpago"]
};

const BASIC_HISTORY_QUESTIONS = {
    "Quem foi o primeiro presidente do Brasil?": ["Deodoro da Fonseca", "Getúlio Vargas", "Dom Pedro II", "Juscelino Kubitschek"],
    "Quem descobriu o Brasil?": ["Pedro Álvares Cabral", "Dom Pedro I", "Cristóvão Colombo", "Vasco da Gama"],
    "Em que ano o Brasil foi descoberto?": ["1500", "1492", "1822", "1889"],
    "Quem proclamou a Independência do Brasil?": ["Dom Pedro I", "Dom João VI", "Getúlio Vargas", "Tiradentes"],
    "Em que ano foi proclamada a Independência do Brasil?": ["1822", "1889", "1500", "1808"],
    "Quem foi Tiradentes?": ["Um líder da Inconfidência Mineira", "Imperador do Brasil", "Presidente", "Explorador português"],
    "O que foi a escravidão?": ["Trabalho forçado de pessoas", "Guerra civil", "Imposto pago", "Festival cultural"],
    "Em que ano foi abolida a escravidão no Brasil?": ["1888", "1822", "1500", "1890"],
    "Quem assinou a Lei Áurea?": ["Princesa Isabel", "Dom Pedro II", "Dom João VI", "Getúlio Vargas"],
    "Quem era o imperador na época da Independência?": ["Dom Pedro I", "Dom Pedro II", "Dom João VI", "Getúlio Vargas"],
    "Qual foi a primeira capital do Brasil?": ["Salvador", "Rio de Janeiro", "Brasília", "São Paulo"],
    "Qual é a atual capital do Brasil?": ["Brasília", "Rio de Janeiro", "Salvador", "São Paulo"],
    "Em que ano foi proclamada a República no Brasil?": ["1889", "1822", "1500", "1891"],
    "Quem foi Zumbi dos Palmares?": ["Líder quilombola", "Presidente", "Explorador português", "Imperador"],
    "O que eram os quilombos?": ["Refúgios de escravos fugidos", "Cidades antigas", "Praças de guerra", "Portos comerciais"],
    "O que foi a Inconfidência Mineira?": ["Movimento pela independência", "Descobrimento do Brasil", "Fundação de Brasília", "Abolição da escravidão"],
    "Quem foi Dom Pedro II?": ["Segundo imperador do Brasil", "Presidente do Brasil", "Explorador português", "Líder quilombola"],
    "O que significa o grito do Ipiranga?": ["Independência do Brasil", "Descobrimento do Brasil", "Abolição da escravidão", "Proclamação da República"],
    "Por que Brasília foi construída?": ["Para ser a nova capital do Brasil", "Para ser uma cidade turística", "Por causa do ouro", "Para exportação de café"],
    "Quando Brasília foi inaugurada?": ["1960", "1889", "1822", "1500"],
    "Quem foi responsável pela construção de Brasília?": ["Juscelino Kubitschek", "Dom Pedro II", "Getúlio Vargas", "Pedro Álvares Cabral"],
    "O que foi a Revolução Industrial?": ["Período de máquinas e fábricas", "Guerra", "Independência", "Descobrimento do Brasil"],
    "Qual povo construiu as pirâmides do Egito?": ["Egípcios", "Romanos", "Gregos", "Chineses"],
    "O que eram as capitanias hereditárias?": ["Divisão de terras no Brasil colonial", "Terras dos índios", "Reinos africanos", "Cidades antigas"],
    "Quem foram os povos indígenas?": ["Primeiros habitantes do Brasil", "Portugueses", "Africanos", "Franceses"],
    "O que é cultura?": ["Costumes e tradições de um povo", "Só comida", "Somente músicas", "Apenas roupas"],
    "O que foi a Ditadura Militar no Brasil?": ["Período sem democracia", "Descobrimento", "Independência", "Guerra mundial"],
    "Quem foi Getúlio Vargas?": ["Presidente do Brasil", "Imperador", "Explorador", "Rei"],
    "O que significa feriado de 7 de setembro?": ["Independência do Brasil", "Descobrimento", "Proclamação da República", "Abolição da escravidão"],
    "Quem são os Bandeirantes?": ["Exploradores do interior do Brasil", "Imperadores", "Índios", "Reis europeus"],
    "O que foi o ciclo do ouro?": ["Período de exploração de ouro no Brasil", "Plantação de café", "Construção de Brasília", "Proclamação da República"],
    "Quem são os ancestrais dos brasileiros indígenas?": ["Povos nativos das Américas", "Portugueses", "Africanoss", "Europeus"],
    "O que é arqueologia?": ["Estudo de civilizações antigas", "Física", "Biologia", "Meteorologia"],
    "Quem foi Cristóvão Colombo?": ["Navegador que chegou à América", "Imperador do Brasil", "Presidente", "Líder quilombola"],
    "O que foi o Período Colonial no Brasil?": ["Quando o Brasil era colônia de Portugal", "Quando era república", "Depois da independência", "Na ditadura"],
    "Qual desses povos é da Antiguidade?": ["Romanos", "Brasileiros", "Portugueses", "Ingleses modernos"],
    "O que são museus?": ["Locais que guardam história", "Supermercados", "Academias", "Postos de gasolina"],
    "O que significa patrimônio histórico?": ["Bem que faz parte da história", "Loja antiga", "Praia famosa", "Praça esportiva"],
    "O que foi a Revolução Francesa?": ["Movimento que derrubou a monarquia na França", "Independência do Brasil", "Descobrimento da América", "Fim da escravidão"],
    "Quem foram os faraós?": ["Reis do Egito Antigo", "Presidente do Brasil", "Imperadores romanos", "Exploradores portugueses"],
    "Qual desses é um símbolo do Brasil?": ["Bandeira", "Muro", "Carro", "Porta"],
    "Por que estudamos história?": ["Para entender o passado", "Só para decorar", "Para fazer contas", "Para ver filmes"],
    "O que é cidadania?": ["Direitos e deveres de um cidadão", "Comprar coisas", "Viajar", "Ser turista"],
    "Qual destes é um marco da história do Brasil?": ["Independência", "Uma corrida", "Um festival musical", "Um jogo de futebol"],
    "O que foi o descobrimento da América?": ["Chegada de Colombo ao continente americano", "Independência do Brasil", "Construção das pirâmides", "Proclamação da República"],
    "Por que Dom João VI veio para o Brasil?": ["Fugindo das guerras na Europa", "Turismo", "Abolir a escravidão", "Proclamar a república"],
    "O que foi o período imperial no Brasil?": ["Tempo em que o Brasil teve imperadores", "Período das cavernas", "Ditadura", "Colonização africana"],
    "O que significa revolução?": ["Mudança rápida e grande", "Comer muito", "Andar em círculo", "Viajar"],
    "Quem são os heróis da pátria?": ["Pessoas que contribuíram para o Brasil", "Super-heróis de filme", "Jogadores de futebol", "Atores"],
    "Por que é importante preservar a história?": ["Para conhecer o passado e aprender com ele", "Para guardar tudo no museu", "Para fazer festas", "Para tirar fotos"]
};

const BASIC_GEOGRAPHY_QUESTIONS = {
    "Qual é o maior país do mundo em extensão territorial?": ["Rússia", "Brasil", "China", "Estados Unidos"],
    "Qual é o país onde vivemos?": ["Brasil", "Argentina", "Portugal", "Estados Unidos"],
    "Qual é a capital do Brasil?": ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador"],
    "O que é um continente?": ["Uma grande extensão de terra", "Um rio", "Uma cidade", "Uma montanha"],
    "Quantos continentes existem?": ["6", "4", "7", "5"],
    "Qual é o continente onde está o Brasil?": ["América do Sul", "África", "Europa", "Ásia"],
    "Qual é o maior oceano do mundo?": ["Oceano Pacífico", "Oceano Atlântico", "Oceano Índico", "Oceano Ártico"],
    "O que é um rio?": ["Um curso de água", "Uma montanha", "Uma estrada", "Uma cidade"],
    "O que é uma floresta?": ["Grande área com muitas árvores", "Praia", "Deserto", "Cidade"],
    "O que é um mapa?": ["Representação de um lugar", "Livro de histórias", "Brinquedo", "Animal"],
    "O que é a linha do Equador?": ["Linha imaginária que divide a Terra ao meio", "Rio da Amazônia", "Rua famosa", "Montanha no Brasil"],
    "Qual é o maior estado do Brasil?": ["Amazonas", "São Paulo", "Bahia", "Minas Gerais"],
    "O que são os pontos cardeais?": ["Norte, Sul, Leste e Oeste", "Água, fogo, terra e ar", "Carros, aviões, navios e trens", "Verão, inverno, outono e primavera"],
    "O que é uma bússola?": ["Instrumento que indica direção", "Telefone", "Livro", "Câmera"],
    "Qual é o maior deserto do mundo?": ["Deserto do Saara", "Deserto da Antártida", "Deserto do Atacama", "Deserto de Gobi"],
    "O que é um vulcão?": ["Montanha que libera lava", "Rio de água quente", "Floresta tropical", "Montanha de gelo"],
    "Qual é o principal rio do Brasil?": ["Rio Amazonas", "Rio São Francisco", "Rio Paraná", "Rio Tocantins"],
    "O que é uma cachoeira?": ["Queda de água", "Montanha de neve", "Prédio muito alto", "Deserto"],
    "O que é um continente onde está a África?": ["África", "América", "Ásia", "Oceania"],
    "O que é urbanização?": ["Crescimento das cidades", "Plantar na roça", "Fazer trilhas", "Criar animais"],
    "O que são zonas rurais?": ["Áreas no campo", "Centros das cidades", "Praias movimentadas", "Capitais dos países"],
    "O que são zonas urbanas?": ["Áreas das cidades", "Fazendas", "Rios", "Florestas"],
    "Qual é o bioma da Amazônia?": ["Floresta Tropical", "Caatinga", "Pampas", "Pantanal"],
    "O que são fusos horários?": ["Divisão da Terra em horas diferentes", "Lugares que fazem muito calor", "Rios e lagos", "Cidades grandes"],
    "O que é clima?": ["Condições do tempo ao longo dos anos", "Chuva do dia", "Relâmpago", "Terremoto"],
    "O que é relevo?": ["Formas da superfície da Terra", "Roupas de inverno", "Alimentos típicos", "Rios e mares"],
    "Qual é o ponto mais alto do mundo?": ["Monte Everest", "Monte Roraima", "Pico da Neblina", "Montanha dos Andes"],
    "O que é um arquipélago?": ["Conjunto de ilhas", "Grande deserto", "Floresta tropical", "Cadeia de montanhas"],
    "O que é o Pantanal?": ["Maior planície alagável do mundo", "Deserto", "Vulcão", "Praia"],
    "O que é a Caatinga?": ["Bioma do sertão nordestino", "Floresta Amazônica", "Pantanal", "Pampas"],
    "Qual é a função de uma rosa dos ventos?": ["Indicar as direções", "Medir chuva", "Fazer comida", "Desenhar mapas"],
    "O que é o Cerrado?": ["Bioma de savana brasileira", "Floresta de pinheiros", "Pantanal", "Deserto"],
    "O que significa desmatamento?": ["Destruição das florestas", "Construção de casas", "Criação de animais", "Plantação de árvores"],
    "Por que é importante preservar os rios?": ["Para garantir água limpa", "Para construir ruas", "Para criar carros", "Para fazer prédios"],
    "O que são recursos naturais?": ["Tudo que vem da natureza", "Prédios", "Carros", "Computadores"],
    "Qual é o menor continente do mundo?": ["Oceania", "Ásia", "Europa", "África"],
    "Onde se localiza o deserto do Atacama?": ["Chile", "Brasil", "Argentina", "Peru"],
    "O que são ilhas?": ["Porções de terra cercadas de água", "Montanhas no meio do deserto", "Cidades no interior", "Florestas tropicais"],
    "O que são placas tectônicas?": ["Grandes blocos que formam a crosta terrestre", "Rios subterrâneos", "Montanhas de gelo", "Nuvens muito pesadas"],
    "Por que ocorrem terremotos?": ["Movimento das placas tectônicas", "Vento muito forte", "Chuva intensa", "Relâmpagos constantes"],
    "Qual é a linha imaginária que divide os hemisférios norte e sul?": ["Linha do Equador", "Trópico de Câncer", "Meridiano de Greenwich", "Trópico de Capricórnio"],
    "O que é o Meridiano de Greenwich?": ["Linha que divide os hemisférios leste e oeste", "Rio da Europa", "Montanha da África", "Cidade na Inglaterra"],
    "O que é latitude?": ["Distância em graus da linha do Equador", "Altura da montanha", "Profundidade do oceano", "Peso de uma rocha"],
    "O que é longitude?": ["Distância em graus do Meridiano de Greenwich", "Comprimento de um rio", "Tamanho de uma ilha", "Altura de uma árvore"],
    "O que é uma estação do ano?": ["Período com características de clima específicas", "Cidade turística", "Montanha famosa", "Ilha deserta"],
    "Quais são as quatro estações do ano?": ["Verão, outono, inverno e primavera", "Chuva, sol, vento e neve", "Frio, calor, vento e tempestade", "Seca, enchente, granizo e neblina"],
    "O que é uma fronteira?": ["Limite entre dois territórios", "Praia com muitas ondas", "Rio muito grande", "Rua de uma cidade"],
    "O que é uma paisagem natural?": ["Lugar formado pela natureza", "Prédio moderno", "Aeroporto", "Shopping center"],
    "O que é uma paisagem modificada?": ["Lugar transformado pelos seres humanos", "Floresta intocada", "Rio selvagem", "Montanha natural"],
    "Por que é importante cuidar do meio ambiente?": ["Para garantir qualidade de vida", "Para construir mais prédios", "Para aumentar o desmatamento", "Para destruir florestas"]
};

const BASIC_ART_QUESTIONS = {
    "O que é arte?": ["Expressão de ideias e sentimentos", "Apenas pinturas", "Somente músicas", "Só danças"],
    "Qual é o nome do profissional que pinta quadros?": ["Pintor", "Cantor", "Dançarino", "Ator"],
    "O que é escultura?": ["Arte de criar formas em 3D", "Pintura", "Música", "Fotografia"],
    "Qual é o nome da mistura de sons organizada?": ["Música", "Pintura", "Dança", "Escultura"],
    "O que é teatro?": ["Representação de histórias com atuação", "Pintura", "Desenho", "Canto"],
    "Qual é o nome do lugar onde os atores se apresentam?": ["Palco", "Museu", "Biblioteca", "Cozinha"],
    "O que é um mural?": ["Pintura em uma parede", "Quadro pequeno", "Desenho em caderno", "Cartaz de cinema"],
    "O que são as cores primárias?": ["Vermelho, azul e amarelo", "Verde, rosa e laranja", "Roxo, cinza e marrom", "Branco, preto e cinza"],
    "Como se forma a cor verde?": ["Misturando azul e amarelo", "Azul e vermelho", "Amarelo e vermelho", "Azul e preto"],
    "Qual é o nome da arte feita com dobraduras de papel?": ["Origami", "Pintura", "Escultura", "Mosaico"],
    "O que é dança?": ["Expressão corporal com movimentos", "Pintura em tela", "Escrever poesias", "Fazer esculturas"],
    "Qual é o nome do lugar onde guardamos obras de arte?": ["Museu", "Supermercado", "Teatro", "Cinemas"],
    "Qual é o nome da técnica que usa pedacinhos para formar imagens?": ["Mosaico", "Origami", "Escultura", "Teatro"],
    "Quem pinta a Monalisa?": ["Leonardo da Vinci", "Pablo Picasso", "Tarsila do Amaral", "Vincent Van Gogh"],
    "Qual é o nome da artista brasileira famosa pela obra 'Abaporu'?": ["Tarsila do Amaral", "Anita Malfatti", "Cândido Portinari", "Heitor Villa-Lobos"],
    "O que é fotografia?": ["Arte de capturar imagens", "Pintura em tela", "Escultura de pedra", "Dança de salão"],
    "O que são instrumentos musicais?": ["Objetos que produzem sons", "Tintas para pintar", "Papéis para dobrar", "Quadros de arte"],
    "O que é cinema?": ["Arte de contar histórias em vídeo", "Dança tradicional", "Música clássica", "Pintura moderna"],
    "Quem é o maestro?": ["Pessoa que conduz uma orquestra", "Pintor", "Ator de cinema", "Escultor"],
    "O que é artesanato?": ["Produção manual de objetos artísticos", "Ato de pintar quadros", "Fotografar paisagens", "Cantar músicas"],
    "Quais são as cores secundárias?": ["Verde, laranja e roxo", "Azul, vermelho e amarelo", "Preto, branco e cinza", "Dourado, prata e bronze"],
    "O que é grafite?": ["Arte feita em muros e paredes urbanas", "Desenho no caderno", "Pintura com tinta óleo", "Dobradura de papel"],
    "O que é uma colagem?": ["Composição feita colando materiais", "Pintura em tela", "Escultura em pedra", "Fotografia antiga"],
    "O que é uma orquestra?": ["Grupo de músicos tocando juntos", "Equipe de pintores", "Grupo de dançarinos", "Companhia de teatro"],
    "O que é performance na arte?": ["Apresentação artística ao vivo", "Desenho em caderno", "Pintura em tela", "Escultura em pedra"],
    "O que é ritmo?": ["Organização dos sons no tempo", "Mistura de cores", "Montagem de quadros", "Criação de esculturas"],
    "Quais são os elementos básicos das artes visuais?": ["Ponto, linha, forma, cor, textura e volume", "Som, cheiro e sabor", "Peso e altura", "Palavras e textos"],
    "O que é expressão corporal?": ["Comunicar-se com movimentos do corpo", "Falar com microfone", "Escrever textos", "Desenhar em papel"],
    "O que é uma galeria de arte?": ["Lugar para expor obras de arte", "Cozinha", "Quadra esportiva", "Supermercado"],
    "O que é arte abstrata?": ["Arte sem representar figuras reais", "Desenho realista", "Fotografia antiga", "Escultura de animais"],
    "O que são instrumentos de percussão?": ["Instrumentos que produzem som quando batemos", "Instrumentos de corda", "Pincéis de pintura", "Papéis de dobradura"],
    "O que é uma maquete?": ["Representação em miniatura de um espaço", "Quadro pintado", "Fotografia antiga", "Peça de teatro"],
    "O que é uma pintura rupestre?": ["Desenhos feitos nas cavernas", "Fotografias antigas", "Esculturas de pedra", "Música tribal"],
    "O que é figurino?": ["Roupas usadas em apresentações", "Quadro de arte", "Instrumento musical", "Dobradura de papel"],
    "O que é cenário?": ["Ambiente onde ocorre uma apresentação", "Quadro famoso", "Música tradicional", "Objeto artesanal"],
    "O que é uma sinfonia?": ["Música composta para orquestra", "Pintura com aquarela", "Desenho em papel", "Dobradura de papel"],
    "O que é iluminação cênica?": ["Uso de luz nas apresentações teatrais", "Luz de casa", "Luz natural do sol", "Lanterna de mão"],
    "O que é uma escultura de barro?": ["Arte feita moldando barro", "Pintura em tela", "Desenho em papel", "Colagem com tecidos"],
    "O que é um retrato?": ["Imagem de uma pessoa", "Foto de animais", "Pintura de frutas", "Escultura de objetos"],
    "O que é harmonia na arte?": ["Equilíbrio entre os elementos da obra", "Som alto", "Movimento rápido", "Uso de cores aleatórias"],
    "O que é um filme de animação?": ["Filme feito a partir de desenhos ou modelos", "Peça de teatro", "Desenho em papel", "Escultura em madeira"],
    "O que é uma instalação artística?": ["Obra que ocupa um espaço físico para interação", "Pintura em papel", "Música clássica", "Teatro de bonecos"],
    "O que é xilogravura?": ["Técnica de gravura em madeira", "Escultura em pedra", "Dobradura de papel", "Pintura com spray"],
    "O que são obras tridimensionais?": ["Têm altura, largura e profundidade", "Apenas largura", "Somente altura", "Som e imagem"],
    "O que é cerâmica?": ["Arte de modelar argila queimada", "Pintura em tela", "Fotografia", "Colagem"],
    "O que é marionete?": ["Boneco movido por fios", "Pintura de paisagem", "Escultura de barro", "Instrumento musical"],
    "O que é uma aquarela?": ["Técnica de pintura com tinta diluída em água", "Escultura em pedra", "Fotografia digital", "Dança clássica"],
    "O que é textura na arte?": ["Sensação visual ou tátil das superfícies", "Som do ambiente", "Cheiro da pintura", "Temperatura do local"],
    "O que é composição na arte?": ["Organização dos elementos visuais", "Criação de sons", "Movimento corporal", "Fotografar objetos"],
    "Por que a arte é importante?": ["Expressa sentimentos, cultura e criatividade", "Serve apenas para decorar", "Faz parte de jogos", "Substitui brinquedos"]
};